import React from "react";
import { InlineMath, BlockMath } from "react-katex";
import "katex/dist/katex.min.css";

const PrintableReport = React.forwardRef(
  ({ results, questions, subjects, userAnswers, examType }, ref) => {
    // Function to render text with LaTeX
    const renderWithLatex = (text) => {
      if (!text) return "";

      const parts = text.split(/(\\\(.*?\\\)|\$\$.*?\$\$)/);

      return parts.map((part, index) => {
        if (part.startsWith("\\(") && part.endsWith("\\)")) {
           const latex = part.substring(2, part.length - 2);
           return <InlineMath key={index} math={latex} />;
        } else if (part.startsWith("$$") && part.endsWith("$$")) {
           const latex = part.substring(2, part.length - 2);
           return <BlockMath key={index} math={latex} />;
        } else {
           return <span key={index}>{part}</span>;
        }
      });
    };

    // Helper to get letter for option index
    const getOptionLetter = (index) => {
      return String.fromCharCode(65 + index); // 0 -> A, 1 -> B, etc.
    };

    // Filter questions by subject
    const getQuestionsBySubject = (subject) => {
      return questions.filter((q) => q.subject === subject);
    };

    return (
      <div
        ref={ref}
        style={{
          padding: "40px",
          fontFamily: "'Inter', 'Helvetica', sans-serif",
          color: "#000",
          backgroundColor: "#fff",
          lineHeight: "1.6", // Good line height for readability
        }}
        className="print-report break-words"
      >
        {/* Print-specific CSS to ensure page breaks and backgrounds */}
        <style>
          {`
            @media print {
              body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
                background-color: white !important;
                color: black !important;
              }
              .page-break {
                page-break-before: always;
              }
              .avoid-break {
                page-break-inside: avoid;
              }
              /* Hide scrollbars during print */
              ::-webkit-scrollbar {
                display: none;
              }
            }
          `}
        </style>

        {/* Header */}
        <div className="text-center mb-10 pb-6 border-b-2 border-gray-300 avoid-break">
          <h1 className="text-4xl font-extrabold mb-2 text-gray-900">
            {examType} Mock Test Report
          </h1>
          <p className="text-lg text-gray-600">Generated by TestSmith</p>
          
          <div className="mt-8 flex justify-center gap-10">
            <div className="bg-gray-100 px-6 py-4 rounded-lg border border-gray-200">
              <p className="text-sm text-gray-500 uppercase font-bold tracking-wider">Total Score</p>
              <p className="text-3xl font-bold text-blue-700">
                {results.overall.totalScore} <span className="text-lg text-gray-500">/ {results.overall.maxPossibleScore}</span>
              </p>
            </div>
            <div className="bg-gray-100 px-6 py-4 rounded-lg border border-gray-200">
              <p className="text-sm text-gray-500 uppercase font-bold tracking-wider">Accuracy</p>
              <p className="text-3xl font-bold text-green-700">
                {results.overall.attemptedCount > 0 
                  ? Math.round(((results.overall.correctMCQ + results.overall.correctNumerical) / results.overall.attemptedCount) * 100) 
                  : 0}%
              </p>
            </div>
          </div>
        </div>

        {/* Result Summary Grid */}
        <div className="mb-10 avoid-break">
          <h2 className="text-2xl font-bold mb-4 text-gray-800 border-b border-gray-200 pb-2">Overall Summary</h2>
          <div className="grid grid-cols-4 gap-4 mb-6">
            <div className="p-4 bg-gray-50 border border-gray-200 rounded text-center">
              <p className="text-gray-500 text-sm font-semibold">Total Questions</p>
              <p className="text-2xl font-bold">{results.overall.totalQuestions}</p>
            </div>
            <div className="p-4 bg-blue-50 border border-blue-200 rounded text-center">
              <p className="text-blue-600 text-sm font-semibold">Attempted</p>
              <p className="text-2xl font-bold text-blue-700">{results.overall.attemptedCount}</p>
            </div>
            <div className="p-4 bg-green-50 border border-green-200 rounded text-center">
              <p className="text-green-600 text-sm font-semibold">Correct</p>
              <p className="text-2xl font-bold text-green-700">{results.overall.correctMCQ + results.overall.correctNumerical}</p>
            </div>
            <div className="p-4 bg-red-50 border border-red-200 rounded text-center">
              <p className="text-red-600 text-sm font-semibold">Incorrect</p>
              <p className="text-2xl font-bold text-red-700">{results.overall.incorrectMCQ + results.overall.incorrectNumerical}</p>
            </div>
          </div>
        </div>

        <div className="page-break"></div>

        {/* Detailed Questions & Answers */}
        {subjects.map((subject, subjectIndex) => {
          const subjectQuestions = getQuestionsBySubject(subject);
          if (subjectQuestions.length === 0) return null;

          return (
            <div key={subject} className={subjectIndex > 0 ? "page-break" : ""}>
              <div className="mb-8 avoid-break border-b-2 border-gray-800 pb-2">
                <h2 className="text-3xl font-bold text-gray-900">{subject}</h2>
                <div className="text-gray-600 mt-2 font-medium">
                  Score: {results.subjectResults[subject].totalScore} / {results.subjectResults[subject].maxPossibleScore}
                </div>
              </div>

              {/* Questions Loop for the Subject */}
              <div className="space-y-8">
                {subjectQuestions.map((q, qIndex) => {
                  const userAnswer = userAnswers[`${subject}-${qIndex}`];
                  const hasAnswered = userAnswer !== undefined;
                  const isMCQ = q.type === "MCQ";
                  
                  let isCorrect = false;
                  if (hasAnswered) {
                    if (isMCQ) {
                      isCorrect = parseInt(userAnswer) === q.correct_answer_index;
                    } else {
                      isCorrect = parseFloat(userAnswer) === parseFloat(q.correct_answer);
                    }
                  }

                  return (
                    <div key={qIndex} className="avoid-break bg-white border border-gray-200 rounded-lg p-6 shadow-sm">
                      <div className="flex gap-4">
                        <div className="w-10 h-10 shrink-0 bg-gray-100 rounded-full flex items-center justify-center font-bold text-gray-700 text-lg">
                          {qIndex + 1}
                        </div>
                        <div className="flex-1">
                          {/* Question Text */}
                          <div className="text-lg font-medium text-gray-900 mb-4 whitespace-pre-wrap">
                            {renderWithLatex(q.question)}
                          </div>

                          {/* Options */}
                          {isMCQ && q.options && (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
                              {q.options.map((opt, optIndex) => {
                                return (
                                  <div key={optIndex} className="p-3 border rounded text-gray-800 flex gap-3 items-start bg-white border-gray-200">
                                    <span className="font-semibold">{getOptionLetter(optIndex)}.</span>
                                    <span className="flex-1 break-words">{renderWithLatex(opt)}</span>
                                  </div>
                                );
                              })}
                            </div>
                          )}

                          {/* Numerical Placeholder */}
                          {!isMCQ && (
                            <div className="mb-4 mt-2">
                              <p className="text-gray-600 font-medium mb-1">Answer Space:</p>
                              <div className="h-10 border-b-2 border-dotted border-gray-400 w-1/3"></div>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Answer Key Table */}
              <div className="mt-12 mb-10 avoid-break">
                <h3 className="text-xl font-bold mb-4 border-b border-gray-300 pb-2 text-gray-800">
                  {subject} - Answer Key
                </h3>
                <div className="overflow-hidden border border-gray-200 rounded-lg">
                  <table className="min-w-full divide-y divide-gray-200 text-sm">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-3 text-left font-bold text-gray-700">Q.No</th>
                        <th className="px-4 py-3 text-left font-bold text-gray-700">Type</th>
                        <th className="px-4 py-3 text-left font-bold text-gray-700">Correct Answer</th>
                        <th className="px-4 py-3 text-left font-bold text-gray-700">Your Answer</th>
                        <th className="px-4 py-3 text-left font-bold text-gray-700">Status</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {subjectQuestions.map((q, qIndex) => {
                        const userAnswer = userAnswers[`${subject}-${qIndex}`];
                        const hasAnswered = userAnswer !== undefined;
                        const isMCQ = q.type === "MCQ";
                        
                        let isCorrect = false;
                        let correctDisplay = "";
                        let userDisplay = "-";

                        if (isMCQ) {
                          correctDisplay = getOptionLetter(q.correct_answer_index);
                          if (hasAnswered) {
                            userDisplay = getOptionLetter(parseInt(userAnswer));
                            isCorrect = parseInt(userAnswer) === q.correct_answer_index;
                          }
                        } else {
                          correctDisplay = q.correct_answer;
                          if (hasAnswered) {
                            userDisplay = userAnswer;
                            isCorrect = parseFloat(userAnswer) === parseFloat(q.correct_answer);
                          }
                        }

                        return (
                          <tr key={qIndex} className={qIndex % 2 === 0 ? "bg-white" : "bg-gray-50"}>
                            <td className="px-4 py-2 font-medium text-gray-900">{qIndex + 1}</td>
                            <td className="px-4 py-2 text-gray-600">{q.type}</td>
                            <td className="px-4 py-2 font-bold text-green-600">{correctDisplay}</td>
                            <td className={`px-4 py-2 font-bold ${hasAnswered ? (isCorrect ? "text-green-600" : "text-red-600") : "text-gray-400"}`}>
                              {userDisplay}
                            </td>
                            <td className="px-4 py-2">
                              {hasAnswered ? (
                                isCorrect ? "✅ Correct" : "❌ Incorrect"
                              ) : (
                                "⬜ Skipped"
                              )}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>

            </div>
          );
        })}
        
        {/* End of Report Footer */}
        <div className="mt-12 pt-8 border-t-2 border-gray-300 text-center text-gray-500 avoid-break">
          <p className="font-semibold">End of Report</p>
          <p className="text-sm mt-1">Generated exclusively for the user on TestSmith</p>
        </div>
      </div>
    );
  }
);

export default PrintableReport;
